// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrbhykiuxrnovljykzfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYmh5a2l1eHJub3ZsanlremZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjI4ODMsImV4cCI6MjA1NjQzODg4M30.ZUsGjuCdTdB8KnM5yMbT_EORzXDWD5WO5j2zIuqVyZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);