name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 7.5.0 # Specify the pnpm version here
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"

    - shell: bash
      run: pnpm install
